### ISSUE TITLE
从Interface取得ipv6地址出现了错误

### ISSUE THREAD

**Issue by Leo357449107** [kkkgo/UE-DDNS#1]
Log:
...
How to get your new IP ?
[1]From IP-Check URL
[2]From Interface
Your choice [1]:
2
[1] eth0 2551:7299::3fc
[2] Enter the network interface manually
...
---------------
对应地址如下
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
...
inet6 fd52:2551:7299::3fc  prefixlen 128  scopeid 0x0<global>

取到了私有地址的一部分

**Comment by kkkgo** [comment]
你好！请问是什么平台呢，网口本身是否有ipv6公网地址？执行`ip addr show eth0`的输出是怎么样的（部分信息可以用xxx代替）？

**Comment by kkkgo** [comment]
已经修复，请再测试下
