### ISSUE TITLE
输入CloudFlare的Global API Key后提示找不到域名

### ISSUE THREAD

**Issue by hugox1337** [kkkgo/UE-DDNS#2]
\=========================================
Universal embedded DDNS Shell Script #
https://github.com/kkkgo/UE-DDNS
https://blog.03k.org/post/ue-ddns.html
\=========================================
[1] cloudflare
[2] dnspod
[3] godaddy
Select your DNS provider[1]:
1
cloudflare DDNS:
[1] IPV4 DDNS
[2] IPV6 DDNS
IPV4/IPV6 DDNS?[1]:
1
[help] https://dash.cloudflare.com/profile/api-tokens
Your cloudflare API TOKEN:
xxxxxxxxxxxxxxxxxxxxxxx
No domain name found for your account!

**Comment by kkkgo** [comment]
出于安全原因，不支持`Global API Keys`，请使用权限更安全的`API Tokens`（脚本提示的也是API Tokens，使用help的连接点过去就可以看到，同时建议只限定ddns子域名的读写）

**Comment by whiterabbit-monster** [comment]
了解了

**Comment by hugox1337** [comment]
> 出于安全原因，不支持`Global API Keys`，请使用权限更安全的`API Tokens`（脚本提示的也是API Tokens，使用help的连接点过去就可以看到，同时建议只限定ddns子域名的读写）

了解了，但脚本提示的是API Tokens，中英文说明提到的是“API KEY”，没接触过CF的用户容易混淆

**Comment by kkkgo** [comment]
> 

😄因为不同的DNS可能叫法不一样，谢谢你的提醒，我稍后修改下文档说明。
