### ISSUE TITLE
钉钉推送失效问题

### ISSUE THREAD

**Issue by caixiaohaier** [kkkgo/UE-DDNS#6]
脚本自带的钉钉机器人推送脚本好像失效了，我添加了token地址进脚本，同时群内机器人设置了加关键字IP，脚本执行提示推送失败。

**Comment by kkkgo** [comment]
sh -x xxx.sh看具体的日志。
钉钉机器人只设置关键字，同时关键字必须包含在推送内容内。

**Comment by kkkgo** [comment]
![image](https://github.com/user-attachments/assets/a3a38353-f219-46cf-8c7c-971828ce90f4)

![image](https://github.com/user-attachments/assets/73185f7e-51df-43f1-97df-82bedcb243da)

问题不存在。
